apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kesha0501/n01736553_CCGC5504_FINAL_EXAM.git
    targetRevision: HEAD
    path: helm/nginx-chart
    helm:
      values: |
        image:
          tag: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
